### ISSUE TITLE
What is "MultiHop" ?

### ISSUE THREAD

**Issue by trendespresso** [0xProject/protocol#506]
https://github.com/0xProject/protocol/blob/4f32f3174f25858644eae4c3de59c3a6717a757c/packages/asset-swapper/src/utils/market_operation_utils/types.ts#L54

I cannot seem to find any information about the DEX "MultiHop." Is this source not an actual DEX but rather the method itself meaning if a user specifies "excludedSources=MultiHop" that only direct pools will be considered for a Swap?

Example:
USDC -> WAVAX -> WBTC would be excluded if "excludedSources=MultiHop"
Or is "MultiHop" an actual DEX somewhere that I simply can't find?

Thanks!

**Comment by abls** [comment]
MultiHop is not a DEX, and it acts pretty much how you described, but excluding it doesn't necessarily mean that a direct swap will be taken. That said, for most use cases it can effectively be treated how you described it... so you can stop reading now if that is all you wanted to know and you can just assume that excluding it excludes everything other than direct swaps. There is just a small detail that might be relevant to some people and I don't want to mislead anyone, so I will explain.

MultiHop consists of a first source swapping from takerToken to an intermediate token, and then a second source swapping from that to the makerToken. The important detail to understand though, is that some sources in these hops might use intermediate tokens regardless of whether or not you include or exclude MultiHop.

**Example**

When you have included the UniswapV2 source, it will try to find paths using intermediate Uniswap V2 pools.
So when you try to do:

`USDC -> WBTC` on UniswapV2

It will try to find Uniswap V2 pools using intermediate tokens, and might end up attempting this as well as the direct path:

`USDC -> WAVAX` + `WAVAX-> WBTC` on UniswapV2

If you also have MultiHop included, it tries using intermediate tokens across multiple sources. This series of swaps on different sources could be attempted:

`USDC -> WAVAX` on UniswapV2
`WAVAX -> WBTC` on UniswapV3

AND this might even happen since UniswapV2 tries to find intermediate pools:

`USDC -> WETH` + `WETH -> WAVAX` on UniswapV2
`WAVAX -> WBTC` on UniswapV3
